/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rudecate.leetcode.longestSubstringWithoutRepeatingCharacters;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class LongestSubstringWithoutRepeatingCharactersTest {
    @Test void appHasAGreeting() {
        LongestSubstringWithoutRepeatingCharacters solution = new LongestSubstringWithoutRepeatingCharacters();
        assertEquals(solution.lengthOfLongestSubstring("abcabcbb"),3);
        assertEquals(solution.lengthOfLongestSubstring("bbbbb"),1);
        assertEquals(solution.lengthOfLongestSubstring("pwwkew"),3);
        assertEquals(solution.lengthOfLongestSubstring(""),0);
    }
}
